// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuYlctXuW6ElGSYYMFPvkWJnrmDgQYAxg',
    appId: '1:155251179050:web:2ed999cfff558419b38d53',
    messagingSenderId: '155251179050',
    projectId: 'matcherapp-418200',
    authDomain: 'matcherapp-418200.firebaseapp.com',
    storageBucket: 'matcherapp-418200.appspot.com',
    measurementId: 'G-7B6CYXJ2Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf0Rulb_Zx20IJm-I2_katuiPR3SZNn9Y',
    appId: '1:155251179050:android:0e0e075e5080bfc4b38d53',
    messagingSenderId: '155251179050',
    projectId: 'matcherapp-418200',
    storageBucket: 'matcherapp-418200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJPGIoctxxXMOn9ZI-00fYjhkc2433W3s',
    appId: '1:155251179050:ios:c98b64a7e0d98decb38d53',
    messagingSenderId: '155251179050',
    projectId: 'matcherapp-418200',
    storageBucket: 'matcherapp-418200.appspot.com',
    iosBundleId: 'com.example.naigationMatcherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJPGIoctxxXMOn9ZI-00fYjhkc2433W3s',
    appId: '1:155251179050:ios:250edc9b80f236d8b38d53',
    messagingSenderId: '155251179050',
    projectId: 'matcherapp-418200',
    storageBucket: 'matcherapp-418200.appspot.com',
    iosBundleId: 'com.example.naigationMatcherApp.RunnerTests',
  );
}
